/*
 * PreemptivePriority.java
 *
 * Created on October 6, 2008, 5:51 PM
 */

/**
 *
 * @author  Administrator
 */
import javax.swing.*;
import java.lang.*;
public class PreemptivePriority extends javax.swing.JFrame {
  
    /** Creates new form PreemptivePriority */
    public PreemptivePriority() {
        initComponents();
    }
    
    PriorityMethod m = new PriorityMethod();
    int[] B = new int[10];
    int[] A = new int[10];
    int[] P = new int[10];
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtP1 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtB1 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtA1 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        btnSave = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        table1 = new javax.swing.JTable();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtAwt = new javax.swing.JTextField();
        txtAtt = new javax.swing.JTextField();
        btnCalculate = new javax.swing.JButton();
        lbl1 = new javax.swing.JLabel();
        lbl2 = new javax.swing.JLabel();
        txtB2 = new javax.swing.JTextField();
        txtA2 = new javax.swing.JTextField();
        txtP2 = new javax.swing.JTextField();
        lbl3 = new javax.swing.JLabel();
        txtB3 = new javax.swing.JTextField();
        txtA3 = new javax.swing.JTextField();
        txtP3 = new javax.swing.JTextField();
        lbl4 = new javax.swing.JLabel();
        txtB4 = new javax.swing.JTextField();
        txtA4 = new javax.swing.JTextField();
        txtP4 = new javax.swing.JTextField();
        lbl5 = new javax.swing.JLabel();
        txtB5 = new javax.swing.JTextField();
        txtA5 = new javax.swing.JTextField();
        txtP5 = new javax.swing.JTextField();
        lbl6 = new javax.swing.JLabel();
        txtB6 = new javax.swing.JTextField();
        txtA6 = new javax.swing.JTextField();
        txtP6 = new javax.swing.JTextField();
        btnNew = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("CPU Scheduling");

        jPanel1.setBackground(new java.awt.Color(0, 204, 204));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Preemptive Priority", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Century Gothic", 1, 11))); // NOI18N

        jLabel1.setFont(new java.awt.Font("Century Gothic", 1, 11));
        jLabel1.setForeground(new java.awt.Color(0, 51, 153));
        jLabel1.setText("Process");

        txtP1.setBackground(new java.awt.Color(255, 255, 204));

        jLabel2.setFont(new java.awt.Font("Century Gothic", 1, 11));
        jLabel2.setForeground(new java.awt.Color(0, 51, 153));
        jLabel2.setText("Burst Time");

        txtB1.setBackground(new java.awt.Color(255, 255, 204));

        jLabel3.setFont(new java.awt.Font("Century Gothic", 1, 11));
        jLabel3.setForeground(new java.awt.Color(0, 51, 153));
        jLabel3.setText("Arrival Time");

        txtA1.setBackground(new java.awt.Color(255, 255, 204));

        jLabel4.setFont(new java.awt.Font("Century Gothic", 1, 11));
        jLabel4.setForeground(new java.awt.Color(0, 51, 153));
        jLabel4.setText("Priority");

        btnSave.setBackground(new java.awt.Color(0, 204, 0));
        btnSave.setFont(new java.awt.Font("Century Gothic", 1, 11));
        btnSave.setForeground(new java.awt.Color(204, 0, 0));
        btnSave.setText("Save");
        btnSave.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSaveMouseClicked(evt);
            }
        });

        table1.setBackground(new java.awt.Color(255, 255, 204));
        table1.setFont(new java.awt.Font("Century Gothic", 1, 11));
        table1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Process", "Burst Time", "Arrival Time", "Priority"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(table1);

        jLabel5.setFont(new java.awt.Font("Century Gothic", 1, 12));
        jLabel5.setForeground(new java.awt.Color(0, 51, 153));
        jLabel5.setText("Average Waiting Time");

        jLabel6.setFont(new java.awt.Font("Century Gothic", 1, 12));
        jLabel6.setForeground(new java.awt.Color(0, 51, 153));
        jLabel6.setText("Average Turning Time");

        txtAwt.setBackground(new java.awt.Color(204, 255, 0));
        txtAwt.setFont(new java.awt.Font("Tahoma", 0, 12));
        txtAwt.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtAwt.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(51, 51, 255), 1, true));

        txtAtt.setBackground(new java.awt.Color(204, 255, 0));
        txtAtt.setFont(new java.awt.Font("Tahoma", 0, 12));
        txtAtt.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtAtt.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(51, 51, 255), 1, true));

        btnCalculate.setBackground(new java.awt.Color(255, 0, 0));
        btnCalculate.setFont(new java.awt.Font("Century Gothic", 1, 11)); // NOI18N
        btnCalculate.setText("Calculate");
        btnCalculate.setEnabled(false);
        btnCalculate.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCalculateMouseClicked(evt);
            }
        });

        lbl1.setFont(new java.awt.Font("Century Gothic", 1, 11));
        lbl1.setForeground(new java.awt.Color(0, 51, 153));
        lbl1.setText("P1");

        lbl2.setFont(new java.awt.Font("Century Gothic", 1, 11));
        lbl2.setForeground(new java.awt.Color(0, 51, 153));
        lbl2.setText("P2");

        txtB2.setBackground(new java.awt.Color(255, 255, 204));

        txtA2.setBackground(new java.awt.Color(255, 255, 204));

        txtP2.setBackground(new java.awt.Color(255, 255, 204));

        lbl3.setFont(new java.awt.Font("Century Gothic", 1, 11));
        lbl3.setForeground(new java.awt.Color(0, 51, 153));
        lbl3.setText("P3");

        txtB3.setBackground(new java.awt.Color(255, 255, 204));

        txtA3.setBackground(new java.awt.Color(255, 255, 204));

        txtP3.setBackground(new java.awt.Color(255, 255, 204));

        lbl4.setFont(new java.awt.Font("Century Gothic", 1, 11));
        lbl4.setForeground(new java.awt.Color(0, 51, 153));
        lbl4.setText("P4");

        txtB4.setBackground(new java.awt.Color(255, 255, 204));

        txtA4.setBackground(new java.awt.Color(255, 255, 204));

        txtP4.setBackground(new java.awt.Color(255, 255, 204));

        lbl5.setFont(new java.awt.Font("Century Gothic", 1, 11));
        lbl5.setForeground(new java.awt.Color(0, 51, 153));
        lbl5.setText("P5");

        txtB5.setBackground(new java.awt.Color(255, 255, 204));

        txtA5.setBackground(new java.awt.Color(255, 255, 204));

        txtP5.setBackground(new java.awt.Color(255, 255, 204));

        lbl6.setFont(new java.awt.Font("Century Gothic", 1, 11));
        lbl6.setForeground(new java.awt.Color(0, 51, 153));
        lbl6.setText("P6");

        txtB6.setBackground(new java.awt.Color(255, 255, 204));

        txtA6.setBackground(new java.awt.Color(255, 255, 204));

        txtP6.setBackground(new java.awt.Color(255, 255, 204));

        btnNew.setBackground(new java.awt.Color(51, 204, 0));
        btnNew.setFont(new java.awt.Font("Century Gothic", 1, 11));
        btnNew.setForeground(new java.awt.Color(204, 0, 0));
        btnNew.setText("New");
        btnNew.setEnabled(false);
        btnNew.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSaveMouseClicked1(evt);
            }
        });

        org.jdesktop.layout.GroupLayout jPanel1Layout = new org.jdesktop.layout.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel1Layout.createSequentialGroup()
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jPanel1Layout.createSequentialGroup()
                        .add(30, 30, 30)
                        .add(jLabel1)
                        .add(32, 32, 32))
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, jPanel1Layout.createSequentialGroup()
                        .add(49, 49, 49)
                        .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                            .add(lbl2)
                            .add(lbl1)
                            .add(lbl3)
                            .add(lbl4)
                            .add(lbl5)
                            .add(lbl6))
                        .add(42, 42, 42)))
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jPanel1Layout.createSequentialGroup()
                        .add(txtB5, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 42, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .add(11, 11, 11))
                    .add(jPanel1Layout.createSequentialGroup()
                        .add(txtB4, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 42, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .add(11, 11, 11))
                    .add(jPanel1Layout.createSequentialGroup()
                        .add(txtB3, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 42, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .add(11, 11, 11))
                    .add(jPanel1Layout.createSequentialGroup()
                        .add(txtB1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 42, Short.MAX_VALUE)
                        .add(11, 11, 11))
                    .add(jLabel2)
                    .add(jPanel1Layout.createSequentialGroup()
                        .add(txtB2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 42, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .add(11, 11, 11))
                    .add(jPanel1Layout.createSequentialGroup()
                        .add(txtB6, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 42, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .add(11, 11, 11)))
                .add(26, 26, 26)
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jPanel1Layout.createSequentialGroup()
                        .add(txtA6, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 42, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .add(39, 39, 39))
                    .add(jPanel1Layout.createSequentialGroup()
                        .add(txtA5, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 42, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .add(39, 39, 39))
                    .add(jPanel1Layout.createSequentialGroup()
                        .add(txtA4, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 42, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .add(39, 39, 39))
                    .add(jPanel1Layout.createSequentialGroup()
                        .add(txtA3, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 42, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .add(39, 39, 39))
                    .add(jPanel1Layout.createSequentialGroup()
                        .add(txtA2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 42, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .add(39, 39, 39))
                    .add(jPanel1Layout.createSequentialGroup()
                        .add(jLabel3)
                        .add(19, 19, 19))
                    .add(jPanel1Layout.createSequentialGroup()
                        .add(txtA1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 42, Short.MAX_VALUE)
                        .add(39, 39, 39)))
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(txtP1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 42, Short.MAX_VALUE)
                    .add(jLabel4)
                    .add(txtP2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 42, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(txtP3, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 42, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(txtP4, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 42, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(txtP5, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 42, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(txtP6, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 42, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .add(236, 236, 236))
            .add(jPanel1Layout.createSequentialGroup()
                .add(177, 177, 177)
                .add(btnNew, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 59, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(16, 16, 16)
                .add(btnSave, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 61, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
            .add(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                    .add(org.jdesktop.layout.GroupLayout.LEADING, jPanel1Layout.createSequentialGroup()
                        .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING, false)
                            .add(jPanel1Layout.createSequentialGroup()
                                .add(jLabel5)
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                .add(txtAwt, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 59, Short.MAX_VALUE))
                            .add(jPanel1Layout.createSequentialGroup()
                                .add(jLabel6)
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                .add(txtAtt, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 60, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))
                        .add(16, 16, 16)
                        .add(btnCalculate, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 87, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                    .add(jScrollPane1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 303, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(229, Short.MAX_VALUE))
        );

        jPanel1Layout.linkSize(new java.awt.Component[] {txtA1, txtB1, txtP1}, org.jdesktop.layout.GroupLayout.HORIZONTAL);

        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jPanel1Layout.createSequentialGroup()
                        .add(jLabel1)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(lbl1))
                    .add(jPanel1Layout.createSequentialGroup()
                        .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                            .add(jLabel2)
                            .add(jLabel3)
                            .add(jLabel4))
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                            .add(txtP1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                            .add(txtB1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                            .add(txtA1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(txtP2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                            .add(txtB2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                            .add(lbl2)))
                    .add(txtA2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(txtP3, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                            .add(txtB3, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                            .add(lbl3)))
                    .add(txtA3, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jPanel1Layout.createSequentialGroup()
                        .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(txtP4, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                            .add(txtA4, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(txtP5, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                            .add(txtA5, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                            .add(txtP6, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                            .add(txtA6, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))
                    .add(jPanel1Layout.createSequentialGroup()
                        .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                            .add(txtB4, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                            .add(lbl4))
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                            .add(txtB5, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                            .add(lbl5))
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                            .add(txtB6, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                            .add(lbl6))))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(btnSave, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 25, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(btnNew, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 25, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .add(17, 17, 17)
                .add(jScrollPane1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 120, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(27, 27, 27)
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jPanel1Layout.createSequentialGroup()
                        .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(jLabel5)
                            .add(txtAwt, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 17, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                            .add(jLabel6)
                            .add(txtAtt, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))
                    .add(btnCalculate, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 38, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 338, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCalculateMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCalculateMouseClicked
// TODO add your handling code here:
        B[1]=Integer.parseInt(txtB1.getText());
        B[2]=Integer.parseInt(txtB2.getText());
        B[3]=Integer.parseInt(txtB3.getText());
        B[4]=Integer.parseInt(txtB4.getText());
        B[5]=Integer.parseInt(txtB5.getText());
        B[6]=Integer.parseInt(txtB6.getText());
        A[1]=Integer.parseInt(txtA1.getText());
        A[2]=Integer.parseInt(txtA2.getText());
        A[3]=Integer.parseInt(txtA3.getText());
        A[4]=Integer.parseInt(txtA4.getText());
        A[5]=Integer.parseInt(txtA5.getText());
        A[6]=Integer.parseInt(txtA6.getText());
        P[1]=Integer.parseInt(txtP1.getText());
        P[2]=Integer.parseInt(txtP2.getText());
        P[3]=Integer.parseInt(txtP3.getText());
        P[4]=Integer.parseInt(txtP4.getText());
        P[5]=Integer.parseInt(txtP5.getText());
        P[6]=Integer.parseInt(txtP6.getText());
        
        String str = String.valueOf(m.AverageWaitingTime(B,A,P));
        Double f = new Double(str);
        double d = f.doubleValue();
        d=d*100.0;
        long dI = (long)d;
        double e = ((double)dI)/100.0;
        
        String str2 = String.valueOf(m.AverageTurningTime(B,A,P));
        Double f2 = new Double(str2);
        double d2 = f2.doubleValue();
        d2=d2*100.0;
        long dI2 = (long)d2;
        double e2 = ((double)dI2)/100.0;
        
        txtAwt.setText(String.valueOf(e));
        txtAtt.setText(String.valueOf(e2));
    }//GEN-LAST:event_btnCalculateMouseClicked

    private void btnSaveMouseClicked1(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSaveMouseClicked1
// TODO add your handling code here:
        txtB1.setText("");
        txtB2.setText("");
        txtB3.setText("");
        txtB4.setText("");
        txtB5.setText("");
        txtB6.setText("");
        txtA1.setText("");
        txtA2.setText("");
        txtA3.setText("");
        txtA4.setText("");
        txtA5.setText("");
        txtA6.setText("");
        txtP1.setText("");
        txtP2.setText("");
        txtP3.setText("");
        txtP4.setText("");
        txtP5.setText("");
        txtP6.setText("");
        txtB1.setEnabled(true);
        txtB2.setEnabled(true);
        txtB3.setEnabled(true);
        txtB4.setEnabled(true);
        txtB5.setEnabled(true);
        txtB6.setEnabled(true);
        txtA1.setEnabled(true);
        txtA2.setEnabled(true);
        txtA3.setEnabled(true);
        txtA4.setEnabled(true);
        txtA5.setEnabled(true);
        txtA6.setEnabled(true);
        txtP1.setEnabled(true);
        txtP2.setEnabled(true);
        txtP3.setEnabled(true);
        txtP4.setEnabled(true);
        txtP5.setEnabled(true);
        txtP6.setEnabled(true);
        btnNew.setEnabled(false);
        btnSave.setEnabled(true);
        txtB1.requestFocus();
        txtAwt.setText("");
        txtAtt.setText("");
        table1.removeAll();
        btnCalculate.setEnabled(false);
    }//GEN-LAST:event_btnSaveMouseClicked1

    private void btnSaveMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSaveMouseClicked
        if(txtB1.getText()=="" || txtB2.getText()=="" || txtB3.getText()=="" || txtB4.getText()=="" || txtB5.getText()=="" || txtB6.getText()=="" || txtA1.getText()=="" || txtA2.getText()=="" || txtA3.getText()=="" || txtA4.getText()=="" || txtA5.getText()=="" || txtA6.getText()=="" || txtP1.getText()=="" || txtP2.getText()=="" || txtP3.getText()=="" || txtP4.getText()=="" || txtP5.getText()=="" || txtP6.getText()=="")
            JOptionPane.showMessageDialog(null,"Filled-up first all fields to continue...");
        else{
            table1.setValueAt(lbl1.getText(),0,0);
            table1.setValueAt(txtB1.getText(),0,1);
            table1.setValueAt(txtA1.getText(),0,2);
            table1.setValueAt(txtP1.getText(),0,3);
            table1.setValueAt(lbl2.getText(),1,0);
            table1.setValueAt(txtB2.getText(),1,1);
            table1.setValueAt(txtA2.getText(),1,2);
            table1.setValueAt(txtP2.getText(),1,3);
            table1.setValueAt(lbl3.getText(),2,0);
            table1.setValueAt(txtB3.getText(),2,1);
            table1.setValueAt(txtA3.getText(),2,2);
            table1.setValueAt(txtP3.getText(),2,3);
            table1.setValueAt(lbl4.getText(),3,0);
            table1.setValueAt(txtB4.getText(),3,1);
            table1.setValueAt(txtA4.getText(),3,2);
            table1.setValueAt(txtP4.getText(),3,3);
            table1.setValueAt(lbl5.getText(),4,0);
            table1.setValueAt(txtB5.getText(),4,1);
            table1.setValueAt(txtA5.getText(),4,2);
            table1.setValueAt(txtP5.getText(),4,3);
            table1.setValueAt(lbl6.getText(),5,0);
            table1.setValueAt(txtB6.getText(),5,1);
            table1.setValueAt(txtA6.getText(),5,2);
            table1.setValueAt(txtP6.getText(),5,3);
            txtB1.setEnabled(false);
            txtB2.setEnabled(false);
            txtB3.setEnabled(false);
            txtB4.setEnabled(false);
            txtB5.setEnabled(false);
            txtB6.setEnabled(false);
            txtA1.setEnabled(false);
            txtA2.setEnabled(false);
            txtA3.setEnabled(false);
            txtA4.setEnabled(false);
            txtA5.setEnabled(false);
            txtA6.setEnabled(false);
            txtP1.setEnabled(false);
            txtP2.setEnabled(false);
            txtP3.setEnabled(false);
            txtP4.setEnabled(false);
            txtP5.setEnabled(false);
            txtP6.setEnabled(false);
            btnNew.setEnabled(true);
            btnSave.setEnabled(false);
            btnCalculate.setEnabled(true);
        }
    }//GEN-LAST:event_btnSaveMouseClicked
      
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PreemptivePriority().setVisible(true);
            }
        });
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCalculate;
    private javax.swing.JButton btnNew;
    private javax.swing.JButton btnSave;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbl1;
    private javax.swing.JLabel lbl2;
    private javax.swing.JLabel lbl3;
    private javax.swing.JLabel lbl4;
    private javax.swing.JLabel lbl5;
    private javax.swing.JLabel lbl6;
    private javax.swing.JTable table1;
    private javax.swing.JTextField txtA1;
    private javax.swing.JTextField txtA2;
    private javax.swing.JTextField txtA3;
    private javax.swing.JTextField txtA4;
    private javax.swing.JTextField txtA5;
    private javax.swing.JTextField txtA6;
    private javax.swing.JTextField txtAtt;
    private javax.swing.JTextField txtAwt;
    private javax.swing.JTextField txtB1;
    private javax.swing.JTextField txtB2;
    private javax.swing.JTextField txtB3;
    private javax.swing.JTextField txtB4;
    private javax.swing.JTextField txtB5;
    private javax.swing.JTextField txtB6;
    private javax.swing.JTextField txtP1;
    private javax.swing.JTextField txtP2;
    private javax.swing.JTextField txtP3;
    private javax.swing.JTextField txtP4;
    private javax.swing.JTextField txtP5;
    private javax.swing.JTextField txtP6;
    // End of variables declaration//GEN-END:variables
    
}
